### ISSUE TITLE
No pictures returned to app after successful login.

### ISSUE THREAD

**Issue by PaddyLevitt** [wheelburra/Clique-Server-Side#1]
picToApp function does not properly return desired picture for current user after successful login

**Comment by PaddyLevitt** [comment]
Added parameters for incoming image collection request in picToApp function.

**Comment by wheelburra** [comment]
You'll have to manually adjust the image path value stored in the
collection. What's in there is local to my machine

Alexander Barrow

**Comment by PaddyLevitt** [comment]
I fixed it just wanted to add some issue tracking for grading purposes.
